/**
 * Report Generator for GuardianRoute AI
 * Creates printable audit PDFs, formatted text briefs, and Markdown reports
 * for commuters and family/guardian sharing.
 */

import { formatCoordinates, formatTimestamp } from './formatters';

/**
 * Generates a clean structured text summary of the route safety audit
 */
export function generateTextAuditReport({
  origin = 'University Main Library',
  destination = 'Westgate Dormitories',
  timeOfDay = 'late_night',
  mode = 'walking',
  safetyResult = {},
  contacts = [],
  userLocation = null,
  hazards = []
}) {
  const score = safetyResult.score || 88;
  const level = safetyResult.level || 'High Safety';
  const metrics = safetyResult.metrics || {};
  const tradeOff = safetyResult.tradeOff?.safest || {};
  const activeHazards = hazards.filter(h => !h.resolved);
  const now = new Date();
  const timestamp = formatTimestamp(now);
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

  return `======================================================================
🛡️ GUARDIANROUTE AI - ROUTE PERSONAL SAFETY AUDIT REPORT
======================================================================
Generated Date : ${dateStr} at ${timestamp}
System Status  : Verified Safe Corridor Engine (AI Model v3.4)
GPS Telemetry  : ${formatCoordinates(userLocation?.lat, userLocation?.lng)}
----------------------------------------------------------------------

1. TRIP OVERVIEW
-----------------
• Origin Location      : ${origin}
• Target Destination  : ${destination}
• Time of Travel      : ${timeOfDay.toUpperCase().replace('_', ' ')}
• Mode of Transport   : ${mode.toUpperCase()}
• Estimated Time      : ${safetyResult.travelTime || '16 mins'} (${safetyResult.distance || '1.4 mi'})

2. COMPOSITE SAFETY SCORE & ASSESSMENT
---------------------------------------
• Overall Safety Score : ${score} / 100 POINTS
• Risk Classification  : [ ${level.toUpperCase()} ]
• AI Recommendation    : ${safetyResult.statusText || 'Optimal Protected Route'}
• Environmental Note   : ${safetyResult.riskSummary || 'Well-lit corridors, active emergency call boxes.'}

3. GRANULAR RISK METRICS BREAKDOWN
-----------------------------------
• Street Luminescence   : ${metrics.lightingScore || 92}% (Municipal & Commercial Lighting)
• Ambient Footfall      : ${metrics.crowdScore || 84}% (Active Pedestrian & Shop Density)
• Emergency Patrol ETA  : ${metrics.responseTime || '2.8 mins'}
• Camera Surveillance   : ${metrics.cameraCoverage || '85%'} (CCTV & Blue-Light Callboxes)
• Hazards on Path Avoided: ${tradeOff.hazardsAvoided || 2} active reported spots bypassed

4. VERIFIED 24/7 SAFE HAVENS ON ROUTE
--------------------------------------
• Metropolitan Police Precinct #1 (0.3 mi) - Tel: +1 (555) 911-0100
• Campus Security HQ Escort Desk  (0.2 mi) - Tel: +1 (555) 888-SAFE
• GreenCross 24/7 Pharmacy Mart   (0.4 mi) - Tel: +1 (555) 432-8800
• Mercy General Trauma ER Center  (0.6 mi) - Tel: +1 (555) 911-0200

5. ARMED EMERGENCY CONTACTS & DISPATCH PAYLOAD
-----------------------------------------------
${contacts.map((c, i) => `  ${i + 1}. ${c.name} (${c.relationship}) - ${c.phone} ${c.isPrimary ? '[PRIMARY SOS]' : ''}`).join('\n')}

6. ACTIVE COMMUNITY HAZARD ADVISORY
------------------------------------
${activeHazards.length === 0 ? '  No critical blockers currently logged on this route corridor.' : activeHazards.map((h, i) => `  [#${i + 1}] ${h.title} (${h.severity} Severity) - ${h.location}`).join('\n')}

======================================================================
Report generated by GuardianRoute AI. Share with family or emergency contacts.
Official Verification Portal: https://guardianroute.ai/verify
======================================================================`;
}

/**
 * Downloads a structured .txt file
 */
export function downloadTextReport(reportData) {
  const content = generateTextAuditReport(reportData);
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `GuardianRoute_Safety_Audit_${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Triggers a professional styled print / PDF dialog
 */
export function printStyledPdfReport(reportData) {
  const content = generateTextAuditReport(reportData);
  const printWindow = window.open('', '_blank', 'width=800,height=900');
  if (!printWindow) return;

  const score = reportData.safetyResult?.score || 88;
  const level = reportData.safetyResult?.level || 'High Safety';
  const badgeColor = score >= 80 ? '#10b981' : score >= 50 ? '#f59e0b' : '#f43f5e';

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>GuardianRoute AI - Safety Audit Report</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.5;
            color: #1e293b;
            padding: 30px;
            max-width: 780px;
            margin: 0 auto;
          }
          .header {
            border-bottom: 2px solid #0f172a;
            padding-bottom: 16px;
            margin-bottom: 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
          }
          .brand {
            font-size: 24px;
            font-weight: 800;
            color: #0284c7;
          }
          .score-box {
            background: #f8fafc;
            border: 2px solid ${badgeColor};
            border-radius: 12px;
            padding: 16px;
            text-align: center;
            margin: 20px 0;
          }
          .score-num {
            font-size: 42px;
            font-weight: 900;
            color: ${badgeColor};
          }
          .grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 16px;
            margin: 20px 0;
          }
          .card {
            background: #f1f5f9;
            padding: 14px;
            border-radius: 8px;
          }
          .card h4 {
            margin: 0 0 6px 0;
            color: #334155;
            font-size: 13px;
            text-transform: uppercase;
          }
          pre {
            background: #f8fafc;
            padding: 14px;
            border-radius: 8px;
            border: 1px solid #e2e8f0;
            font-size: 11px;
            white-space: pre-wrap;
          }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="brand">🛡️ GuardianRoute AI</div>
            <div style="font-size: 12px; color: #64748b;">Personal Safety & Commuter Risk Audit</div>
          </div>
          <div style="text-align: right; font-size: 11px; color: #64748b;">
            Date: ${new Date().toLocaleDateString()}<br/>
            GPS: ${formatCoordinates(reportData.userLocation?.lat, reportData.userLocation?.lng)}
          </div>
        </div>

        <div class="score-box">
          <div style="font-size: 12px; text-transform: uppercase; font-weight: bold; color: #64748b;">Calculated Safety Score</div>
          <div class="score-num">${score} / 100</div>
          <div style="font-weight: bold; color: ${badgeColor}; text-transform: uppercase;">${level}</div>
        </div>

        <div class="grid">
          <div class="card">
            <h4>Route Itinerary</h4>
            <p style="margin: 0; font-size: 13px;"><strong>Origin:</strong> ${reportData.origin}</p>
            <p style="margin: 4px 0 0 0; font-size: 13px;"><strong>Destination:</strong> ${reportData.destination}</p>
            <p style="margin: 4px 0 0 0; font-size: 12px; color: #64748b;">Mode: ${reportData.mode} | Time: ${reportData.timeOfDay}</p>
          </div>
          <div class="card">
            <h4>Environmental Metrics</h4>
            <p style="margin: 0; font-size: 13px;">Lighting: <strong>${reportData.safetyResult?.metrics?.lightingScore || 92}%</strong></p>
            <p style="margin: 4px 0 0 0; font-size: 13px;">Crowd Density: <strong>${reportData.safetyResult?.metrics?.crowdScore || 84}%</strong></p>
            <p style="margin: 4px 0 0 0; font-size: 13px;">Patrol ETA: <strong>${reportData.safetyResult?.metrics?.responseTime || '2.8 mins'}</strong></p>
          </div>
        </div>

        <h3>Full Audit Transcript</h3>
        <pre>${content}</pre>

        <div class="no-print" style="margin-top: 20px; text-align: center;">
          <button onclick="window.print()" style="padding: 10px 24px; background: #0284c7; color: #fff; border: none; border-radius: 8px; font-weight: bold; cursor: pointer;">
            🖨️ Print / Save as PDF
          </button>
        </div>
      </body>
    </html>
  `);
  printWindow.document.close();
}
